let bulletsPattern = {
    0: {
        x: 0,
        y: 0,
        damage: 1,
        speed: 40,
        velocity: -2,
        vector: [-1, 0],
        theta: 0,
        radius: 4,
        color: "red"
    },
    1: {
        x: 0,
        y: 0,
        speed: 40,
        damage: 1,
        velocity: -2,
        vector: [1, 0],
        theta: 0,
        radius: 4,
        color: "red"
    },
    2: {
        x: 0,
        y: 0,
        speed: 40,
        damage: 1,
        velocity: -1,
        vector: [0, 1],
        theta: 0,
        radius: 5,
        color: "red"
    },
    3: {
        x: 0,
        y: 0,
        speed: 40,
        damage: 1,
        velocity: -1,
        vector: [0, Math.sqrt(1) *-1],
        theta: 0,
        radius: 4,
        color: "red"
    },
    4: {
        x: 0,
        y: 0,
        speed: 34,
        damage: 1,
        velocity: -1.2,
        vector: [Math.sqrt(1) * -1, Math.sqrt(1) *-1],
        theta: 0,
        radius: 4,
        color: "red",
    },
    5: {
        x: 0,
        y: 0,
        speed: 34,
        damage: 1,
        velocity: -1.2,
        vector: [Math.sqrt(1), Math.sqrt(1)],
        theta: 0,
        radius: 4,
        color: "red",
    },
    6: {
        x: 0,
        y: 0,
        speed: 34,
        damage: 1,
        velocity: -1.2,
        vector: [Math.sqrt(1),Math.sqrt(1) * -1],
        theta: 0,
        radius: 4,
        color: "red",
    },
    7: {
        x: 0,
        y: 0,
        speed: 34,
        damage: 1,
        velocity: -1.2,
        vector: [Math.sqrt(1) * -1, Math.sqrt(1)],
        theta: 0,
        radius: 4,
        color: "red",
    },

}

module.exports = bulletsPattern;